[package]
name = "commons-rs"
version = "0.1.0"
authors = ["niuchangqing <ncq1993@188.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
